-- Insertar Categorías
INSERT INTO categoria (nombre, descripcion) VALUES
('Novela', 'Obras de ficción narrativa extensa, de carácter literario.'),
('Ciencia Ficción', 'Género literario basado en futuros alternativos y avances científicos.'),
('Desarrollo de Software', 'Libros sobre programación, arquitectura de software y mejores prácticas.'),
('Fantasía', 'Narraciones literarias sobre mundos imaginarios, seres mitológicos y magia.'),
('Historia', 'Acontecimientos del pasado, biografías históricas y análisis social.'),
('Desarrollo Personal', 'Libros sobre autoayuda, productividad, finanzas personales y hábitos.'),
('Misterio y Suspenso', 'Novelas policiales, intrigas criminales, suspenso y terror.'),
('Poesía', 'Obras líricas, antologías de poemas y versos literarios.'),
('Filosofía', 'Ensayos existenciales, tratados de ética, moral y corrientes de pensamiento.'),
('Divulgación Científica', 'Matemática, física, astronomía y ciencias explicadas de forma amena.'),
('Biografías', 'Relatos detallados de la vida de personas notables.'),
('Arte y Fotografía', 'Libros sobre teoría del arte, historia del arte y colecciones fotográficas.'),
('Medicina y Salud', 'Guías de salud, anatomía, nutrición y divulgación médica.'),
('Viajes y Geografía', 'Guías de viajes, exploraciones geográficas y relatos de aventuras.'),
('Deportes y Nutrición', 'Libros sobre actividad física, deportes, rendimiento y alimentación.'),
('Economía y Finanzas', 'Tratados económicos, finanzas globales e historia de los mercados.'),
('Infantil y Juvenil', 'Literatura orientada a niños y adolescentes, fábulas y cuentos.'),
('Teología y Religión', 'Estudios teológicos, historia de las religiones y textos sagrados.'),
('Teatro', 'Obras dramáticas, guiones teatrales y tragedias clásicas.'),
('Derecho', 'Leyes, jurisprudencia, tratados constitucionales y derecho penal.');

-- Insertar Autores
INSERT INTO autor (nombre, biografia, fecha_nacimiento) VALUES
('Gabriel García Márquez', 'Escritor y periodista colombiano. Máximo exponente del realismo mágico y premio Nobel de Literatura en 1982.', '1927-03-06'),
('J.R.R. Tolkien', 'Escritor, filólogo, poeta y profesor universitario británico. Famoso por su legendarium de fantasía épica.', '1892-01-03'),
('Joshua Bloch', 'Ingeniero de software estadounidense. Lideró el diseño e implementación de diversas plataformas y APIs de Java.', '1961-08-28'),
('Stephen King', 'Escritor estadounidense prolífico, conocido mundialmente por sus novelas de terror, ficción sobrenatural y misterio.', '1947-09-21'),
('Yuval Noah Harari', 'Historiador y filósofo israelí, profesor en la Universidad Hebrea de Jerusalén, autor de best-sellers mundiales.', '1976-02-24'),
('Robert C. Martin', 'Ingeniero de software y autor estadounidense. Es uno de los padres del Manifiesto Ágil y creador de los principios SOLID.', '1952-12-05'),
('Agatha Christie', 'Escritora y dramaturga británica, especialista en el género policial y creadora de personajes emblemáticos como Hércules Poirot.', '1890-09-15'),
('Mario Vargas Llosa', 'Escritor, político y periodista peruano. Premio Nobel de Literatura en 2010 por su excelsa narrativa de la realidad social.', '1936-03-28'),
('Carl Sagan', 'Astrónomo, astrofísico, cosmólogo y divulgador científico estadounidense, defensor del pensamiento escéptico y el método científico.', '1934-11-09'),
('Friedrich Nietzsche', 'Filósofo, poeta y filólogo alemán, considerado uno de los pensadores contemporáneos más influyentes del siglo XIX.', '1844-10-15'),
('Jane Austen', 'Novelista británica cuyas obras retratan la sociedad de principios del siglo XIX.', '1775-12-16'),
('Isaac Asimov', 'Escritor y bioquímico estadounidense, conocido por sus obras de ciencia ficción y divulgación.', '1920-01-02'),
('Virginia Woolf', 'Escritora británica, destacada figura del modernismo vanguardista del siglo XX.', '1882-01-25'),
('Edgar Allan Poe', 'Escritor, poeta y crítico estadounidense, célebre por sus cuentos de terror y misterio.', '1809-01-19'),
('Albert Camus', 'Novedoso escritor y filósofo francés, Premio Nobel de Literatura en 1957.', '1913-11-07'),
('H.P. Lovecraft', 'Escritor estadounidense de relatos de terror y ciencia ficción, creador del horror cósmico.', '1890-08-20'),
('Arthur Conan Doyle', 'Escritor y médico británico, célebre creador del mundialmente famoso detective Sherlock Holmes.', '1859-05-22'),
('Julio Verne', 'Escritor francés de novelas de aventuras y ciencia ficción, visionario de la tecnología moderna.', '1828-02-08'),
('Ernest Hemingway', 'Escritor y periodista estadounidense, uno de los principales novelistas del siglo XX.', '1899-07-21'),
('Franz Kafka', 'Escritor bohemio en lengua alemana, cuya obra es una de las más influyentes de la literatura universal.', '1883-07-03');

-- Insertar Libros
INSERT INTO libro (titulo, isbn, stock, categoria_id) VALUES
('Cien años de soledad', '978-0307474728', 10, 1),
('El Señor de los Anillos', '978-8445071755', 5, 4),
('Effective Java', '978-0134685991', 8, 3),
('IT', '978-1501142970', 4, 7),
('Sapiens: De animales a dioses', '978-8499926223', 12, 5),
('Clean Code', '978-0132350884', 15, 3),
('Asesinato en el Orient Express', '978-8467035544', 6, 7),
('La ciudad y los perros', '978-8420471839', 8, 1),
('Cosmos', '978-8408061250', 7, 10),
('Así habló Zaratustra', '978-8420633190', 5, 9),
('El Hobbit', '978-8445071410', 9, 4),
('El resplandor', '978-8497931038', 6, 7),
('Orgullo y prejuicio', '978-0141439518', 8, 1),
('Fundación', '978-0553293357', 12, 2),
('Al faro', '978-0156030076', 6, 1),
('El gato negro y otros relatos', '978-8420651262', 15, 7),
('El extranjero', '978-8420636948', 9, 9),
('La llamada de Cthulhu', '978-8441319851', 11, 7),
('Estudio en escarlata', '978-8497930819', 14, 7),
('Veinte mil leguas de viaje submarino', '978-8420674179', 10, 2);

-- Asociar Libros con Autores en la tabla intermedia libro_autor
INSERT INTO libro_autor (libro_id, autor_id) VALUES 
(1, 1),
(2, 2),
(3, 3),
(4, 4),
(5, 5),
(6, 6),
(7, 7),
(8, 8),
(9, 9),
(10, 10),
(11, 2),
(12, 4),
(13, 11),
(14, 12),
(15, 13),
(16, 14),
(17, 15),
(18, 16),
(19, 17),
(20, 18);

-- Insertar Usuarios
INSERT INTO usuario (nombre, email, telefono, direccion) VALUES
('Andy Gonzales', 'andy.gonzales@gmail.com', '987654321', 'Av. Larco 123, Lima'),
('Maria Lopez', 'maria.lopez@gmail.com', '912345678', 'Calle Las Flores 456, Arequipa'),
('Carlos Perez', 'carlos.perez@gmail.com', '934567890', 'Jr. Trujillo 789, Trujillo'),
('Ana Gomez', 'ana.gomez@gmail.com', '945678123', 'Av. Arequipa 1450, Lima'),
('Juan Castro', 'juan.castro@gmail.com', '956781234', 'Calle San Francisco 320, Cusco'),
('Sofia Martinez', 'sofia.martinez@gmail.com', '967812345', 'Av. Balta 789, Chiclayo'),
('Luis Rodriguez', 'luis.rodriguez@gmail.com', '978123456', 'Calle Melgar 105, Arequipa'),
('Elena Davila', 'elena.davila@gmail.com', '989012345', 'Av. Salaverry 2100, Lima'),
('Pedro Sanchez', 'pedro.sanchez@gmail.com', '990123456', 'Jr. Junin 432, Huancayo'),
('Laura Torres', 'laura.torres@gmail.com', '911234567', 'Calle Real 654, Ica'),
('Gabriel Soto', 'gabriel.soto@gmail.com', '922334455', 'Av. Javier Prado 450, Lima'),
('Rosa Espinoza', 'rosa.espinoza@gmail.com', '933445566', 'Calle Santa Marta 102, Arequipa'),
('Miguel Diaz', 'miguel.diaz@gmail.com', '944556677', 'Jr. Bolognesi 504, Piura'),
('Carmen Rivas', 'carmen.rivas@gmail.com', '955667788', 'Av. El Sol 820, Cusco'),
('Daniela Vargas', 'daniela.vargas@gmail.com', '966778899', 'Calle Real 140, Huancayo'),
('Jorge Benitez', 'jorge.benitez@gmail.com', '977889900', 'Av. Pardo 920, Chimbote'),
('Patricia Vega', 'patricia.vega@gmail.com', '988990011', 'Calle San Jose 305, Chiclayo'),
('Manuel Ruiz', 'manuel.ruiz@gmail.com', '999001122', 'Av. Los Incas 412, Trujillo'),
('Lucia Mendez', 'lucia.mendez@gmail.com', '911002233', 'Jr. Ayacucho 112, Cajamarca'),
('Roberto Ortiz', 'roberto.ortiz@gmail.com', '922003344', 'Calle Tacna 604, Tacna');
